apiVersion: v1
kind: Service
metadata:
    namespace: challenge1
    name: jenkins-service
spec:
    type: LoadBalancer
    selector:
        app: build
    ports:
        - port: 80
          name: jenkins
          targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: challenge1
    name: jenkins-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: build
    template:
        metadata:
            labels:
                app: build
        spec:
            containers:
            -   name: jenkins
                image: reblank/jenkins-challenge1
                envFrom:
                    - secretRef:
                          name: jenkins-secrets
                env:
                  - name: SLACK_TEAM_DOMAIN
                    value: revaturetrain-cx22851
                volumeMounts:
                  - name: docker-sock
                    mountPath: /var/run/docker.sock
            restartPolicy: Always  
            volumes:
              - name: docker-sock
                hostPath:
                  path: /var/run/docker.sock

    