apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-agent
  namespace: challenge1
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deploy
rules:
- apiGroups: [""]
  resources: ["pods", "replicasets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec","replicasets/exec", "deployments/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["create","delete","get","list","patch","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubectl-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy
subjects:
- kind: ServiceAccount
  name: kubectl-agent
  namespace: challenge1